---
- name: copy test
  hosts: yc0227client2
  sudo: yes
  sudo_user: root
  gather_facts: no
  
  tasks:
    - name: copy a file
      win_copy:
        src: /home/administrator/reboot.sh
        dest: C:\
